### ISSUE TITLE
RuntimeException on Raspberry Pi

### ISSUE THREAD

**Issue by Whitespace** [heronarts/P3LX#7]
I'm on a Raspberry Pi 4 with Processing 3.5.3.  I'm trying to run LXStudio headlessly, without the UI.  When I try to run a freshly-cloned LXStudio via `xvfb` I get:

```
xvfb-run /usr/local/bin/processing-java --sketch=/home/pi/Desktop/LXStudio/LXStudio --run

OpenGL error 1280 at bot beginDraw(): invalid enumerant
java.lang.RuntimeException: Cannot compile vertex shader:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

	at processing.core.PGraphics.showException(PGraphics.java:8316)
	at processing.opengl.PShader.compileVertexShader(PShader.java:981)
	at processing.opengl.PShader.compile(PShader.java:917)
	at processing.opengl.PShader.init(PShader.java:894)
	at processing.opengl.PShader.bind(PShader.java:351)
	at heronarts.p3lx.ui.component.UIGLPointCloud.onDraw(Unknown Source)
	at heronarts.p3lx.ui.UIObject.draw(Unknown Source)
	at heronarts.p3lx.ui.UI3dContext.draw(Unknown Source)
	at heronarts.p3lx.ui.UIObject.draw(Unknown Source)
	at heronarts.p3lx.ui.UI.draw(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1432)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1425)
	at processing.core.PApplet.handleMethods(PApplet.java:1624)
	at processing.core.PApplet.handleDraw(PApplet.java:2488)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

This also happens if I run it through the Processing UX.

**Comment by mcslee** [comment]
Hey Tom - sorry about this, the LX Studio UI uses a custom shader that isn't supported on Raspberry Pi. If you're running headless on a Raspberry Pi, the best thing to do is actually to not invoke the LXStudio class, which will still end up instantiating all the UI.

Rather, you can create a headless project with your code, there's an example here:
https://github.com/heronarts/LX/tree/master/LX-example-headless

You can invoke that directly as simple command-line java and it won't load *any* processing UI stuff whatsoever.

Alternatively, I have a newer version of LXStudio that lets you pass a flag to not use the custom shader. But this isn't out on a public release just yet. If the above doesn't work for you and you want to try this other version, shoot me an email at mcslee@gmail.com and I can pass you a link to that.

**Comment by Whitespace** [comment]
Thanks!  Closing this then.
